## 一、简单的捕获异常语法

```py
try:

尝试执行的代码

except:

出现错误的处理

### 错误类型捕获

try:

    # 尝试执行的代码
    pass

except 错误类型1:

    # 针对错误类型1，对应的代码处理
    pass

except (错误类型2, 错误类型3):

    # 针对错误类型2 和 3，对应的代码处理
    pass

except Exception as result:

    print("未知错误 %s" % result)
```

- 当 Python 解释器 抛出异常 时，最后一行错误信息的第一个单词，就是错误类型

---

## 二、异常捕获完整语法

- 在实际开发中，为了能够处理复杂的异常情况，完整的异常语法如下：

> 提示：
> 
> - 有关完整语法的应用场景，在后续学习中，结合实际的案例会更好理解
> 
> - 现在先对这个语法结构有个印象即

```py
try:

    # 尝试执行的代码
    pass
except 错误类型1:

    # 针对错误类型1，对应的代码处理
    pass

except 错误类型2:

    # 针对错误类型2，对应的代码处理
    pass

except (错误类型3, 错误类型4):

    # 针对错误类型3 和 4，对应的代码处理
    pass

except Exception as result:

    # 打印错误信息
    print(result)
    #打印报错位置
    traceback.print_exc()

else:

    # 没有异常才会执行的代码
    pass

finally:

    # 无论是否有异常，都会执行的代码

    print("无论是否有异常，都会执行的代码")
```

- else 只有在没有异常时才会执行的代码

- finally 无论是否有异常，都会执行的代码

---

## 三、异常的传递

- 异常的传递 —— 当 函数/方法 执行 出现异常，会 将异常传递 给 函数/方法 的 调用一方

- 如果 传递到主程序，仍然 没有异常处理，程序才会被终止

> 提示
> 
> - 在开发中，可以在主函数中增加 异常捕获
> 
> - 而在主函数中调用的其他函数，只要出现异常，都会传递到主函数的 异常捕获 中
> 
> - 这样就不需要在代码中，增加大量的 异常捕获，能够保证代码的整洁

## 四、抛出异常

- Python 中提供了一个 Exception 异常类

- 在开发时，如果满足 特定业务需求时，希望 抛出异常，可以：
1. 创建 一个 Exception 的 对象

2. 使用 raise 关键字 抛出 异常对象

需求

- 定义 input_password 函数，提示用户输入密码

- 如果用户输入长度 < 8，抛出异常

- 如果用户输入长度 >=8，返回输入的密码

```py
def input_password():

    # 1. 提示用户输入密码

    pwd = input("请输入密码：")

    # 2. 判断密码长度，如果长度 >= 8，返回用户输入的密码

    if len(pwd) >= 8:

        return pwd

    # 3. 密码长度不够，需要抛出异常

    # 1> 创建异常对象 - 使用异常的错误信息字符串作为参数

    ex = Exception("密码长度不够")

    # 2> 抛出异常对象

    raise ex

try:

    user_pwd = input_password()

    print(user_pwd)

except Exception as result:

    print("发现错误：%s" % result)
```

